---
- name: install nginx last version
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - nginx
  ignore_errors: true
  
#create directory for website inside
- name: Create Directory for website
  file:
    path: /var/www/html/website
    owner: "{{ user.user }}"
    group: "{{ user.group }}"
    state: directory
    mode: 0755

- name: change nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: "{{ user.user }}"
    group: "{{ user.group }}"
    mode: 0755

- name: Change virtualhost to my virtualhost
  template:
    src: site.conf.j2
    dest: "/etc/nginx/conf.d/{{ site.domain }}.conf"
    owner: "{{ user.user }}"
    group: "{{ user.group }}"
    mode: 0755

- name: startup nginx
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
# tasks file for nginx