---
- name: install php of definied version
  apt:
    name: "php{{ php-fpm.version }}-fpm"

- name: change php-fpm.ini config
  template:
    src: php.ini.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: 0755
